builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64
    main: ./
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
      - -s -w
      - -X github.com/tcpaddock/shiplot/cmd.version={{ .Version }}
      - -X github.com/tcpaddock/shiplot/cmd.buildTarget={{ .Os }}_{{ .Arch }}
      - -X github.com/tcpaddock/shiplot/cmd.buildDate={{.Date}}
archives:
  -
    format_overrides:  
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - example.shiplot.yaml