name: alpha
on:
  push:
    branches:
      - 'alpha'
  pull_request:
    branches:
      - 'alpha'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: golangci/golangci-lint-action@v3
  release:
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          allow-initial-development-versions: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}