name: Release Main
on:
  push:
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          custom-arguments: --provider-opt github_use_compare_commits=true
          allow-initial-development-versions: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}