name: Release
on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Install semantic-release
        run: npm install
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release